[rpc_endpoints]
mumbai = "${MUMBAI_RPC_URL}"
polygon = "${POLYGON_RPC_URL}"
ethereum = "${ETHEREUM_RPC_URL}"
bsc = "${BSC_RPC_URL}"

[etherscan]
polygon = { key = "${POLYGONSCAN_API_KEY}", chain = "137" }
v-bsc-890 = { key = "${TENDERLY_ACCESS_TOKEN}", chain = "890", url = "${BSC_RPC_URL}/verify/etherscan" }
etherscan = { key = "${ETHEREUMSCAN_API_KEY}", chain = "1" }
v-mainnet888scan = { key = "${TENDERLY_ACCESS_TOKEN}", chain = "888", url = "${ETHEREUM_RPC_URL}/verify/etherscan" }

[profile.default]
solc = "0.8.27"
src = "src"
out = "out"
libs = ["lib"]
cbor_metadata = true
evmVersion = "cancun"
build_info = true
extra_output = ["storageLayout"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
