[rpc_endpoints]
mumbai = "${MUMBAI_RPC_URL}"
polygon = "${POLYGON_RPC_URL}"
ethereum = "${ETHEREUM_RPC_URL}"

[etherscan]
mumbai = { key = "${POLYGONSCAN_API_KEY}", chain = "80001" }
polygon = { key = "${POLYGONSCAN_API_KEY}", chain = "137" }
etherscan = { key = "${ETHEREUMSCAN_API_KEY}", chain = "1" }
v-mainnet888scan = { key = "ow43E49ce6DQR--95rzFX3K7esqyoati", chain = "888", url = "https://virtual.mainnet.rpc.tenderly.co/c5ed9a3b-7ad5-4d6a-8e4b-76a4b00ba6ea/verify/etherscan" }

[profile.default]
solc = "0.8.25"
src = "src"
out = "out"
libs = ["lib"]
cbor_metadata = true
evmVersion = "shanghai"
build_info = true
extra_output = ["storageLayout"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
