name: Solidity Tests

on:
  pull_request:
    branches:
      - main
      - test
      - live
  push:
    branches:
      - main
      - test
      - live
  workflow_dispatch:      

jobs:
  tests:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Display branch information
        run: |
          echo "Running on branch: ${{ github.ref_name }}"
          if [[ -n "${{ github.base_ref }}" ]]; then
            echo "Target branch for pull request: ${{ github.base_ref }}"
          else
            echo "Not running on a pull request"
          fi

      - name: Install Foundry5
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Determine Environment Prefix
        id: env_prefix
        run: |
          BRANCH=${{ github.base_ref }}  # This is set for pull requests
          [ -z "$BRANCH" ] && BRANCH=main  # Fallback to main branch if not a pull request
          PREFIX=$(echo $BRANCH | awk -F'-' '{print toupper($1)}')  # Extract prefix and convert to upper case
          echo "PREFIX=$PREFIX" >> $GITHUB_ENV
          echo "PREFIX=$PREFIX"

      - name: Set environment variables
        run: |
          echo "ETHEREUM_RPC_URL=${{ vars[format('{0}_ETHEREUM_RPC_URL', steps.env_prefix.outputs.PREFIX)] }}" >> $GITHUB_ENV
          echo "POLYGON_RPC_URL=${{ vars[format('{0}_POLYGON_RPC_URL', steps.env_prefix.outputs.PREFIX)] }}" >> $GITHUB_ENV
          echo "ETHEREUM_SALT=${{ vars[format('{0}_ETHEREUM_SALT', steps.env_prefix.outputs.PREFIX)] }}" >> $GITHUB_ENV
          echo "POLYGON_SALT=${{ vars[format('{0}_POLYGON_SALT', steps.env_prefix.outputs.PREFIX)] }}" >> $GITHUB_ENV
          echo "ETH_4337_FACTORY=${{ vars[format('{0}_ETH_4337_FACTORY', steps.env_prefix.outputs.PREFIX)] }}" >> $GITHUB_ENV
          echo "ETH_4337_ACCOUNT=${{ vars[format('{0}_ETH_4337_ACCOUNT', steps.env_prefix.outputs.PREFIX)] }}" >> $GITHUB_ENV
          echo "ETHEREUM_PRIVATE_KEY=${{ secrets[format('{0}_ETHEREUM_PRIVATE_KEY', steps.env_prefix.outputs.PREFIX)] }}" >> $GITHUB_ENV
          echo "POLYGON_PRIVATE_KEY=${{ secrets[format('{0}_POLYGON_PRIVATE_KEY', steps.env_prefix.outputs.PREFIX)] }}" >> $GITHUB_ENV

      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes
        
      - name: Run Forge tests
        run: forge test -vvv
        env:
          ETHEREUM_PRIVATE_KEY: ${{ secrets[format('{0}_ETHEREUM_PRIVATE_KEY', steps.env_prefix.outputs.PREFIX)] }}
          POLYGON_PRIVATE_KEY: ${{ secrets[format('{0}_POLYGON_PRIVATE_KEY', steps.env_prefix.outputs.PREFIX)] }}

      - name: Run coverage
        run: forge coverage --report lcov
        
      - name: Upload coverage report 
        uses: codecov/codecov-action@v3
        with:
          files: ./lcov.info
          fail_ci_if_error: true
          flags: unittests
